## Thank you for submitting your code!
## Please ensure this checklist is complete before creating the pull request.

- [ ] All of my data files are named `<site_ID>_data*.csv`
- [ ] All columns are present in my data file(s)
- [ ] All columns are named properly
- [ ] Data are coded according to the data dictionary
- [ ] All measures are within the appropriate scales and distribution

To check boxes, change `- [ ]` to `- [x]`

Once you create the pull request, we will automatically check your data files. \
If the test fails, you can see the output:
1. Click `Details` next to the failed job
2. Click `Run script` to view the output of the QC checks